### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Cuteistfox**

### CODE REVIEW

**Comment by cooolgamer** [comment]
Oh yeah this is a very important change, I hope it get merged 🙏

**Comment by Cuteistfox** [comment]
i want review perms to review it

**Comment by NexusSfan** [comment]
Wait you forgot to fix the file its supposed to say this

# Hello this is scam website

**Comment by legoskid** [comment]
W pull request

**Review by cooolgamer — APPROVED** [review]
approved

**Comment by NexusSfan** [comment]
MERGE IT NOW

**Comment by Cuteistfox** [comment]
The more aprovalls this gets, the more likley we will get a merge

**Comment by NexusSfan** [comment]
yes we need to contact 1games dot io to merge the request

**Review by NexusSfan — APPROVED** [review]
Geometry Lite is going to be angry after the gd cologne raid... who cares though

**Review by ghost — APPROVED** [review]

**Pull request closed without merging**
