### PR TITLE
Add Gorilla Adventure

### PR DESCRIPTION
**Pull request by GDColon**
I realized that Gorilla Adventure was missing from your collection of games, so I added it for you 🥰

### CODE REVIEW

**Comment by pauliesnug** [comment]
gorilla adventure is my favorite hit indie AAAA mobile game to play with friends

**Comment by fancythedeveloper** [comment]
LGTM ‼️‼️‼️😍😍😍😍👍👍👍👍👍

**Comment by ghost** [comment]
imagine they actually merge this

**Review by ghost — APPROVED** [review]

**Comment by Centri3** [comment]
merge quick :3

**Review by SuperchupuDev — APPROVED** [review]
LGTM

**Comment by S-PScripts** [comment]
GD Cologne is the best

**Comment by LNLenost** [comment]
> I realized that Gorilla Adventure was missing from your collection of games, so I added it for you 🥰

ISTG if they merge this I'm going to join your channel memebership

**Comment by yoann256** [comment]
Bruh why Gorilla Adventure is cool

**Comment by vingaming1113** [comment]
lgtm :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket: :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket: :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket: :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:

**Comment by vingaming1113** [comment]
NOOO ITS CLOSED

**Comment by AsahiRocks** [comment]
LGTM 👍

**Pull request closed without merging**
